name: backup repo
on:
  push:
    branches:
      - master
jobs:
  back-up-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to CodeCommit
        uses: Equiem/sync-up-to-codecommit-action@v1.0.14
        with:
          repository_name: ${{ github.event.repository.name }}
